services:
  - type: web
    name: email-ai
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn src.web.app:app  # Update to your app's entry point
